apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-ozzyib-nodejs App
name: labs-ozzyib-nodejs
home: https://github.com/hmcts/labs-ozzyib-nodejs
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.4.16
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
